from constants.k_endpoints import *
from constants.k_atributos import *

LISTADO_LIBRO_ATRIBUTOS = [LIBRO_ID, LIBRO_TITULO, LIBRO_AUTOR, LIBRO_FECHA_INICIO, LIBRO_FECHA_FIN, LIBRO_VALORACION, LIBRO_OPINION]
LISTADO_LIBRO_ENDPOINTS = [CONSULTAR_LIBROS, AGREGAR_LIBRO, MODIFICAR_LIBRO, ELIMINAR_LIBRO, RANKING_LIBRO, FICHATECNICA_LIBRO]
    